### ISSUE TITLE
TOT Connect needs updating for 1.1

### ISSUE THREAD

**Issue by gittywithexcitement** [Arrowstar/ksptot#10]
Hi! Great tool; thanks for making it.

With the KSP 1.1 update, it seems that part(s) of TOT Connect no longer function. The 'upload selected DV maneuver' no longer works. No maneuver node is created in the game, and no error is reported either.

The debug menu in KSP says:

> [Exception]: TypeLoadException: Could not load type 'Vector3d' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

What I've tested and still works:

- Get orbit of active vessel
- Get masses of active vessel

P.S. You should add KSP TOT Connect as a github repository, or as a subfolder of this repository :smile:

**Comment by gittywithexcitement** [comment]
I have fixed the issue, and I'd send you a pull request if TOT Connect was part of this (or some other) github repository. Once you upload Connect, I'll send the pull request. :smile: 

The fix was pretty simple:

- The paths to a few assemblies need to be added, and the current assemblies need to point to the KSP_x64_Data.
- I fixed a couple of compile errors. One was easy. The other I had to disable a small feature because I don't know where something moved.

**Comment by Arrowstar** [comment]
Hey, could you just send me the updated files on the forum?  I'm having issues getting KSPTOTConnect on here. 

Did you fix the conversion from degrees to radians for true anomaly, by the way?

**Comment by gittywithexcitement** [comment]
> Hey, could you just send me the updated files on the forum?

Check your forum inbox.

> Did you fix the conversion from degrees to radians for true anomaly, by the way?

No, didn't know about that.

**Comment by Arrowstar** [comment]
I don't see anything in my forum inbox?

**Comment by gittywithexcitement** [comment]
I emailed you the updated files.

**Comment by Arrowstar** [comment]
Currently working an issue with KSPTOTConnect and the x64 version of KSP.  Hey, gittywithexcitement, if you have the time and expertise, would you be interested in helping me investigate?  I'm really stuck.

Link to the issue description here: http://forum.kerbalspaceprogram.com/index.php?/topic/33568-winmac-ksp-trajectory-optimization-tool-v150-optimizations/&do=findComment&comment=2559660

**Comment by gittywithexcitement** [comment]
I fixed the LFQueue, by making it a locked queue. Tested and TOTConnect works fine now. So there must be an error in the old LFQueue, but I don't see the value in debugging it. It's not as if TOT needs a super high performance queue (that I'm aware of).

Also, I don't think KSP uses .NET Framework 4.0. I think it's still on 3.5.

I'm happy to submit a pull request with the updates. I know you said you were having trouble 'getting KSPTOTConnect on here'. Would you like me to submit a PR that adds TOTConnect to this repository? Would you like it in its own repository?

**Comment by Arrowstar** [comment]
Tell you what, send me the updated file first, then I'll release KSPTOT v151, and then, if you're up for it then, you can create a new repo for KSPTOT Connect with the release code. How does that sound?

**Comment by Arrowstar** [comment]
Issue confirmed resolved.  New build works on KSP x64.  Thanks! :)
