### ISSUE TITLE
Kerbal TOT crash on launch

### ISSUE THREAD

**Issue by justinsandhu** [Arrowstar/ksptot#11]
El Capitan 
Java 6, 2015
Matlab 2013a

Trying to get an error code via console/activity monitor now

**Comment by justinsandhu** [comment]
``Process:               KSPTOT [3656]
Path:                  /Users/USER/Desktop/*/KSPTOT.app/Contents/MacOS/KSPTOT
Identifier:            KSPTOT
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [3650]
Responsible:           KSPTOT [3656]
User ID:               0

Date/Time:             2016-05-10 16:55:57.871 -0700
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        4C7A8D0C-63FB-ADE0-7D0D-E337D8247CCB


Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=.:/Applications/MATLAB/MATLAB_Compiler_Runtime/v81
/Applications/MATLAB/MATLAB_Runtime/v901/runtime/maci64:/Applications/MATLAB/MATLAB_Compiler_Runtime/v81
/Applications/MATLAB/MATLAB_Runtime/v901/bin/maci64:/Applications/MATLAB/MATLAB_Compiler_Runtime/v81
/Applications/MATLAB/MATLAB_Runtime/v901/sys/os/maci64:/System/Library/Frameworks/JavaVM.framework/JavaVM:/System/Library/Frameworks/JavaVM.framework/Libraries

Dyld Error Message:
  Library not loaded: @rpath/libmwlaunchermain.dylib
  Referenced from: /Users/USER/Desktop/*/KSPTOT.app/Contents/MacOS/KSPTOT
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/JavaVM.framework/JavaVM/libmwlaunchermain.dylib: stat() failed with errno=20``

**Comment by Arrowstar** [comment]
Are you running the Mac version?  It looks like something couldn't find a library in the MCR, but I have no idea why that would be.
