### ISSUE TITLE
Cannot extract manoeuvers (I think?) on Mac OS X

### ISSUE THREAD

**Issue by domq** [Arrowstar/ksptot#15]
I have Matlab R2018a and by hook or by crook I managed to rebuild the app. The porkchop plot works fine; however, whenever I attempt to extract manoeuver vectors from that (either from the main screen, or from the multi-flyby screen) I get the following stack trace:

```
Index exceeds array bounds.

Error in doApplyProj (line 23)


Error in applyProjection (line 13)


Error in lambert (line 29)


Error in findOptimalDepartureArrivalObjFunc (line 13)
```
(output truncated)

I truncated at the first line that differs between both situations i.e. when attempting to extract from the multi-flyby screen I would get instead

```
Error in getMultiFlybyXferOrbits (line 41)
```

**Comment by domq** [comment]
I forgot to first thank you for your work.

More info:
- as a total Matlab n00b I may very well be doing it wrong, e.g. I am unable to run the app from the Matlab GUI (I always have to spend 15' repackaging it)
- Since [they say](https://ch.mathworks.com/matlabcentral/answers/136478-using-a-mexw64-function-on-a-mac) I cannot possibly be using the `lambert` function out of any `.mexw64` files, I am guessing the [`lambert` function out of Matlab](https://ch.mathworks.com/help/map/lambert.html) is being used. Perhaps the Matlab one is incompatible with the expectations of KSPTOT? (Again, just guessing)

**Comment by Arrowstar** [comment]
> Since they say I cannot possibly be using the lambert function out of any .mexw64 files, I am guessing the lambert function out of Matlab is being used. Perhaps the Matlab one is incompatible with the expectations of KSPTOT? (Again, just guessing)

Hey there, sorry for the delay.  Anyway, this is exactly what is going on.  You'll need to recompile the lambert solver mex files for OSX before you can continue.  How much experience do you have with MATLAB?  Is this something you think you could figure out on your own?
