### ISSUE TITLE
Wrong order of maneuver vector components after import in Maneuver Execution Assistant

### ISSUE THREAD

**Issue by 1greywind** [Arrowstar/ksptot#19]
KSP TOT version - 1.6.2

STR: 
1
Create maneuver in KSP with components (prograde, normal, radial) = (1, 2, 3)

2
Import maneuver into Maneuver Execution Assistance using "Read next maneuver node from KSP ..." option.

3
Note that imported vector is (3, 1, 2)

Video proof: http://recordit.co/NAFupmQuwt

**Comment by Arrowstar** [comment]
Good find!  Issue resolved in Man. Exe. Assistant for next release.
