### ISSUE TITLE
Remote host address is not persistent in MCC Real Time System "Select Vessel" window.

### ISSUE THREAD

**Issue by 1greywind** [Arrowstar/ksptot#20]
KSP TOT version - 1.6.2

STR:
1
Open KSP TOT and select 

2
Select "MCC Real Time System" item from "KSP Real Time System" menu.

3
Type "192.168.1.1" (or any other address) into "Remote host" input field. Test connection.

4
Close and reopen KSP TOT

5
Note that when you go into MCC Real Time System "Select Vessel" window again, the Remote Host is reset to "localhost"

Why this is important option: KSP TOT is not very stable software and setting up Remote Host again and again when you using KSP TOT over LAN or Internet is frustrating.

Also, it woudn't be nice be able to change connection port (both in MCC settings somewhere and in KSPTOTConnect config).

**Comment by Arrowstar** [comment]
Great find again!  Issue resolved for next release.
