### ISSUE TITLE
LVD Objective Function: "Distance to Ref. Celestial Body" always equals -1

### ISSUE THREAD

**Issue by Josef37** [Arrowstar/ksptot#24]
When trying to minimize distance to a body in LVD, it always equals -1.  
I tried it in a fresh mission and this was the result:

![image](https://user-images.githubusercontent.com/14334266/82371229-1fb4ef00-9a1a-11ea-9802-3bd5a1f0999e.png)

Also there seems to be no way to add a second (or third) objective function. It just won't get added to the list.

Are these known bugs that are about to be resolved?

Thank you,  
Josef

**Comment by Josef37** [comment]
> Also there seems to be no way to add a second (or third) objective function. It just won't get added to the list.

This seems to only happen when you first open the dialog. After clicking "Save & Close" I can add multiple functions

**Comment by Arrowstar** [comment]
This issue has been resolved for the next release.
