### ISSUE TITLE
LVD: Engines not being applied to correct stage, cannot be deleted

### ISSUE THREAD

**Issue by Jakathan** [Arrowstar/ksptot#27]
Using v1.6.8 release, when adding engines to the Vehicle Configuration menu sometimes they do not apply to the assigned stage specified in the "Edit Engine" UI. They seem to apply to the first stage instead. Closing the UI and reloading maintains the correct Assigned Stage value in the "Edit Engine" UI, but does not correctly update the Launch Vehicle Summary. Engines that do this cannot be deleted either.

![image](https://user-images.githubusercontent.com/79614197/130371403-7b303d8a-240f-44c8-af6e-8fe52777c778.png)

It looks to mostly happen when an engine is created on one stage, and then later switched to another.

LVD file that has the issue:
[https://drive.google.com/file/d/1gpTsFe9QL4UlMPntXEBdszwoX8G96zDp/view?usp=sharing](https://drive.google.com/file/d/1gpTsFe9QL4UlMPntXEBdszwoX8G96zDp/view?usp=sharing)

LOG from trying to delete an affected engine:
[ksptot.log](https://github.com/Arrowstar/ksptot/files/7028254/ksptot.log)

**Comment by Jakathan** [comment]
Update: This appears to happen with Tanks as well. Same situation, editing a previously created tank does not update the vehicle summary and unable to delete tank.

**Comment by Arrowstar** [comment]
Thanks for the report, I'm investigating.

**Comment by Arrowstar** [comment]
Issue resolved in patched 1.6.8 release.
