### ISSUE TITLE
A little problem with the display.

### ISSUE THREAD

**Issue by Aebestach** [Arrowstar/ksptot#32]
I don't know if anyone has reported this problem, but when selecting a planet, it appears to disappear. But the data still loads fine. (I may not be explaining this very clearly though, I will use a video below to show what I mean.)

https://github.com/Arrowstar/ksptot/assets/64588584/02242808-125f-41d8-9f8d-43948f159a0c

But this tool is really powerful and great, but I'm still learning how to use it and it does cost a lot to learn.

**Comment by Aebestach** [comment]
Videos can be downloaded and played if they don't play properly.

**Comment by Arrowstar** [comment]
Hey there!  So this isn't a bug, it's actually intended behavior.  All the dropdown does is set the orbital elements correctly.  The idea is that if you change the elements, the name shouldn't still be there, so to get around that quirk, I just have the UI auto set the dropdown menu to the blank element after you use it.

Thanks for the report though!

**Comment by Aebestach** [comment]
Understood, thanks.
