### ISSUE TITLE
700 km orbit is the same as a 70 km one ingame

### ISSUE THREAD

**Issue by TheJewelOfJool** [Arrowstar/ksptot#5]
Title says it all.

**Comment by Arrowstar** [comment]
You'll need to be a bit more specific.

**Comment by TheJewelOfJool** [comment]
Sorry. I was trying some stuff out when I tried to set a 70 km orbit to a KEO one for fun, when I noticed the starting point was coming from inside Kerbin. It happens in multiple tools too.

**Comment by Arrowstar** [comment]
Do you have a non standard bodies file loaded?

**Comment by TheJewelOfJool** [comment]
I'm not sure what that is, but I have 1 bodies file tn the directory I selected for KSPTOT

**Comment by Arrowstar** [comment]
Okay. Can you carefully tell me how to reproduce this, starting at opening mission architect?

**Comment by TheJewelOfJool** [comment]
Actually, I think I misunderstood something. Sorry for bothering you.
