### ISSUE TITLE
Mission Animator azimuth/elevation offset issues

### ISSUE THREAD

**Issue by Gaiiden** [Arrowstar/ksptot#8]
the Azimuth Offset seems itself to be offset by 90 degrees (that figure is rendered at X-Y View), and you can only get 89 degrees on the Elevation Offset which doesn't quite give you a proper top-down view (not sure tho if that's just due to a camera issue and gimbal lock)

http://i.imgur.com/h8yb9J0.png

**Comment by Arrowstar** [comment]
Elevation limitation of 89 degrees is due to gimbal lock, can't do anything about that. :)

I'll look into the Az offset.

**Comment by Arrowstar** [comment]
So the Az offset looks okay to me.  Can you maybe provide me with a picture that illustrates what you mean about it?

**Comment by KSAMissionCtrl** [comment]
I didn't think it was right that I needed to rotate the Azimuth from 0 to 90 degrees to get the Mission Animator top-down view to match what the graph plot showed me from the X-Y view (see image linked in original post).

If that's correct behavior, then nevermind!

**Comment by Arrowstar** [comment]
The azimuth offset is relative to the current source -> destination camera vector, not the absolute X-Y-Z coordinate system.  If you think about it like that, does it make more sense? :)

**Comment by KSAMissionCtrl** [comment]
not really. It's pretty much why I never got into 3D modeling or programming ever. But if you say so! :)

**Comment by Arrowstar** [comment]
It's correct, you'll just have to trust me on this one. :)
